- submissions/api.py
- submissions/tests/test_api.py
Ignore the submissions that have 0 score.
https://openedx.atlassian.net/browse/TNL-1125
> Ignore the submissions that have 0 score.

- submissions/api.py
- submissions/tests/test_api.py
- submissions/tests/test_read_replica.py
Cancelled submissions should not be returned in top_submissions method.
https://openedx.atlassian.net/browse/TNL-1455
> The Top submissions should not be including the cancelled ones.

- setup.py
- submissions/models.py
> Remove RemovedInDjango19Warning warnings

- setup.py
> Update the submission version.

- submissions/models.py
@andy-armstrong @efischer19 
This is to fix the warnings you were seeing.
> Add new app_label to ScoreAnnotation.

- setup.py
> Version 0.1.4

- setup.py
Sibling to https://github.com/edx/edx-ora2/pull/886.
edx-submissions is rather stable, and should be bumped to a 1.0.0 release.
Can I get some quick thumbs per our HipChat discussion?
@andy-armstrong @cahrens @robrap @dianakhuang
> Update versioning to 1.0.0

- requirements.txt
- setup.py
> Tell requirements.txt to pin current edx-platform django version

- requirements.txt
- setup.py
@macdiesel @cahrens 
Same issue as https://github.com/edx/edx-ora2/pull/920
> Allow a range of django versions

- setup.py
- submissions/api.py
- submissions/models.py
- submissions/tests/test_api.py
- submissions/tests/test_reset_score.py
- test-requirements.txt
> send created time

- .gitignore
- .travis.yml
- README.rst
- settings.py
- setup.py
- submissions/tests/test_read_replica.py
- test-requirements.txt
- tox-requirements.txt
- tox.ini
Upgrade django_nose; Mock out read_replica for testing (see https://code.djangoproject.com/ticket/23718)
Reviewers:
FYI Reviewers:
@edx/educator-all
> EDUCATOR-786 | Support Django 1.11

- setup.py
Simple version bump from 2.0.3 to 2.0.4.
@iloveagent57 @efischer19 FYI
> Version bump to 2.0.4

- setup.py
- submissions/api.py
Actually show the field errors upon the exception.
@efischer19 @iloveagent57 Please review.
> Fix exception printing and log upon error.

- requirements.txt
- setup.py
Blocks https://github.com/edx/edx-ora2/pull/1030
> Update installed version of jsonfield

- setup.py
- submissions/api.py
- submissions/management/commands/update_submissions_uuids.py
- submissions/tests/test_api.py
This will assume new-style (hex) strings on disk, with a transparent fallback to old-style (hyphenated) strings on failure.
Very much in-progress
> Data is in multiple states on prod

- requirements.txt
- setup.py
- submissions/management/commands/update_submissions_uuids.py
This reverts the revert I recently made, which was needed to get a hotfix out without blowing up requirements. Now that we look to be out of the woods there, this change can go back into master in anticipation of edx-ora2 2.0.0.
I'll also likely be adding some management command improvements to this PR, since I'm here.
> Return to normalcy

- requirements.txt
- submissions/api.py
As part of [DEPR-9](https://openedx.atlassian.net/browse/DEPR-9)
> Remove datadog integration.

- .travis.yml
- tox.ini
Proposed fix for https://openedx.atlassian.net/browse/INCR-86
> [INCR-86] Support testing Python 3 in edx-submissions 

- docs/source/conf.py
- manage.py
- pycodestyle
- settings.py
- setup.py
- submissions/admin.py
- submissions/api.py
- submissions/management/commands/update_submissions_uuids.py
- submissions/migrations/0001_initial.py
- submissions/migrations/0002_auto_20151119_0913.py
- submissions/migrations/0003_submission_status.py
- submissions/migrations/0004_remove_django_extensions.py
- submissions/models.py
- submissions/serializers.py
- submissions/tests/test_api.py
- submissions/tests/test_models.py
- submissions/tests/test_read_replica.py
- submissions/tests/test_reset_score.py
- submissions/tests/test_serializers.py
- submissions/urls.py
- submissions/views.py
- test-requirements.txt
- tox.ini
Fixes: https://openedx.atlassian.net/browse/INCR-97
$ __python-modernize -w .__
Upgrading __ddt__ and __freezegun__ will fail the Travis tests.
> [INCR-97] Upgrade dependencies in edx-submissions

- submissions/tests/test_api.py
- test-requirements.txt
> INCR-109: Upgrade ddt

- submissions/tests/test_api.py
- test-requirements.txt
Fix broken test by ensuring all datetimes are timezone aware.
@edx/incr-reviewers
> INCR-110: Upgrade freezegun

- submissions/migrations/0001_initial.py
- submissions/migrations/0003_submission_status.py
- submissions/models.py
> INCR-111: Fix migrations

- .travis.yml
- requirements/base.in
- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/docs.txt
- requirements/pip-tools.txt
- requirements/test.txt
- settings.py
- setup.py
- submissions/__init__.py
- submissions/management/commands/analyze_uploaded_file_sizes.py
- submissions/migrations/0001_initial.py
- submissions/models.py
- tox.ini
Relevant JIRA issue can be found [here](https://openedx.atlassian.net/browse/BOM-1223).
> Replaced jsonfield with jsonfield2

- submissions/__init__.py
forgot to increase version in https://github.com/edx/edx-submissions/pull/110
> bump version for team_api changes

- submissions/__init__.py
- submissions/serializers.py
- submissions/team_api.py
- submissions/tests/test_team_api.py
We need to return answer as part of create_team_submission.
> Return answer as part of submissions team API

- .travis.yml
- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/docs.txt
- requirements/pip-tools.txt
- requirements/test.txt
- setup.py
- submissions/__init__.py
- tox.ini
**JIRA:** [BOM-1544](https://openedx.atlassian.net/browse/BOM-1544)
> BOM-1544: Added python 3.8 in test matrix

- Makefile
- submissions/__init__.py
- submissions/admin.py
some dev QOL improvements
1.copied alex's `install-local-ora` to create a `install-local-submissions` make command 
2.also added a django admin view for TeamSubmissions
> add makefile command and admin tools

- submissions/__init__.py
- submissions/api.py
Jira: [EDUCATOR-5017](https://openedx.atlassian.net/browse/EDUCATOR-5017)
FYI: @edx/masters-devs-gta
> Set score as an atomic transaction

- .gitignore
- requirements/base.txt
- requirements/dev.txt
- requirements/docs.txt
- requirements/pip-tools.txt
- requirements/test.in
- requirements/test.txt
- requirements/tox.txt
- requirements/travis.txt
- settings.py
- submissions/tests/test_api.py
**Description:**
- Replace nose with pytest.
- Update packages with "make upgrade"
> [BD-18] Replace nose with pytest

- submissions/__init__.py
- submissions/team_api.py
- submissions/tests/test_team_api.py
Don't create new submissions for a learner that has an existing team submission.
[Jira](https://openedx.atlassian.net/browse/EDUCATOR-5210)
> EDUCATOR-5210 

- submissions/__init__.py
- submissions/team_api.py
Additional logging around team submissions. Team submissions are being created without individual submissions and I don't know why.
> feat: additional team submission logging

- submissions/tests/test_team_api.py
Unit test for  get_team_ids_by_team_submission_uuid
> test: added test for get_team_ids_by_team_submission_uuid

- .github/workflows/upgrade-python-requirements.yml
**Description:** change requirements upgrade email to new aurora support
**JIRA:** [AU-778](https://2u-internal.atlassian.net/browse/AU-778)
> build: change requirements upgrade email

- submissions/__init__.py
I can't just re-release the same version, gotta skip to the next version
> chore: bump version

- .github/workflows/ci.yml
- .github/workflows/migrations-check.yml
cf https://discuss.openedx.org/t/codecov-upload-breakages/12877, https://github.com/openedx/axim-engineering/issues/1125
> build: update codecov action version

- .github/workflows/ci.yml
- .github/workflows/migrations-check.yml
- related to https://github.com/openedx/public-engineering/issues/313
> Drop usage of ubuntu-20.04
