AUTHORS, submissions/api.py, submissions/models.py, submissions/tests/test_api.py, submissions/tests/test_reset_score.py
This change introduces two signals that are triggered when the set_score and reset_score operations run successfully. This is part of a larger series of changes that will send signals in the edx-platform code, in order to transmit scores to campus LMS platforms when an assignment is launched over LTI; code in the edx-platform courseware app will catch these signals in order to relay any score changes to the LTI consumer.
Tagging @ormsbee, since we've talked about this change offline.
=> Adding signals for scoring events.

submissions/api.py, submissions/tests/test_api.py
This adds a new API method to edx-submissions:
```python
get_all_submissions(course_id, item_id, item_type, read_replica=True)
```
This method can be used to fetch all student answers to a particular courseware item, e.g. for CSV export.
=> Add get_all_submissions method to the API

requirements.txt
In certain circumstances the version of Pytz in this file will conflict with versions of pytz required by edx-platform in `requirements/edx/base.txt`. This PR makes the version in this repository match.
=> Update pytz to reflect upstream version change

requirements.txt, settings.py, setup.py, submissions/admin.py, submissions/api.py, submissions/migrations/0005_raw_answer_to_jsonfield.py, submissions/models.py, submissions/serializers.py, submissions/tests/test_api.py
* Upgrade DRF to v.3.1
* Use JSONField on the model instead of custom serializer field for the submission answer.
I'm going to hold off on merging this until ORA2 and edx-platform are also upgraded.  Otherwise, it isn't going to be possible to test this end-to-end.
=> Upgrade djangorestframework to v3.1

AUTHORS, submissions/api.py, submissions/migrations/0006_auto__add_scoreannotation__chg_field_studentitem_student_id.py, submissions/models.py, submissions/tests/test_api.py
Add a new `ScoreAnnotation` model for annotating 'special' scores that may exist for reasons outside the typical workflow (for example: staff overrides).
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
FYI: @maxrothman - we're adding a new table here, @ormsbee - just in case you wanted to give it a quick once-over.
=> Add the ability to annotate scores.

requirements.txt, setup.py, test-requirements.txt
Use the same forked version of DRF in the submissions library as edx-platform.
=> Update the DRF version requirement to match edx-platform

submissions/api.py, submissions/migrations/0003_submission_status.py, submissions/models.py, submissions/tests/test_api.py
Previous methods of "deleting state" for a student had just issued
reset scores, so the (unscored) submission was still hanging around.
With this change, the submission can be "deleted" for all django-
relevant purposes, while still remaining in the database in case
it turns out to be interesting to analytics later.
Supersedes https://github.com/edx/edx-submissions/pull/32.
Sibling change to https://github.com/edx/edx-platform/pull/11371 and https://github.com/edx/edx-ora2/pull/862
=> Soft-delete Submissions to reset student state

submissions/api.py, submissions/tests/test_api.py
=> Use score summaries in data download

setup.py, submissions/serializers.py, submissions/tests/test_serializers.py
This is to fix a bug where ORA cannot tell accurately what scores are from staff.
If this gets merged, I'll be sure to handle releasing as well.
=> Serialize annotation information with scores

requirements.txt, setup.py
This is incorrectly downgrading the devstack version when installing ora:
```
Obtaining file:///edx/src/edx-submissions
Collecting pytz==2015.2 (from edx-submissions==1.1.5)
Downloading pytz-2015.2-py2.py3-none-any.whl (476kB)
100% |████████████████████████████████| 481kB 2.6MB/s 
Requirement already satisfied: jsonfield==1.0.3 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from edx-submissions==1.1.5)
Requirement already satisfied: django-extensions==1.5.9 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from edx-submissions==1.1.5)
Requirement already satisfied: django-model-utils==2.3.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from edx-submissions==1.1.5)
Requirement already satisfied: dogapi==1.2.1 in …
```
=> Stop pinning pytz

submissions/api.py
Allows the `score_reset` signal to be silenced during a `reset_score` operation.
=> Allow reset signal to be ignored

requirements.txt, setup.py
As part of the Django 1.11 upgrade of edx-platform, the platform's required version of DRF needs to be upgraded. As this repo is a requirement of edx-platform and is pinned at a lower DRF version, the required version needs to be bumped here as well.
The platform will still use an edX fork of DRF - but that fork is v3.6.3 plus one patch.
=> Upgrade DRF requirement to v3.6.x

submissions/api.py
Log the submission data as well as the errors when the DRF serializer reports the data as invalid.
No urgency for this change - can go out with whatever release is next.
Related to: https://openedx.atlassian.net/browse/LEARNER-1977
=> Log the submission data when validator says invalid.

requirements.txt, settings.py, setup.py, submissions/api.py, submissions/migrations/0001_initial.py, submissions/migrations/0004_remove_django_extensions.py, submissions/models.py, submissions/tests/test_api.py
@doctoryes is this a thing we do, organizationally speaking? I know it adds a bit of risk (what if the package maintainer does something evil with a minor version release?), but if everyone uses semver properly it should allow for easier upgrades. I need to loosen `dogapi` in particular in order to [do something similar for ora's requirements](https://github.com/edx/edx-ora2/blob/32a878fd89e16252275cf25ca42cc2dc1949101a/requirements/tox.txt)
(in the process of a `setup.py install` for edx-ora2)
```
Processing dependencies for ora2==1.4.8
error: dogapi 1.11.1 is installed but dogapi==1.2.1 is required by set(['edx-submissions'])
```
=> Loosen requirements

setup.py, submissions/management/commands/update_submissions_uuids.py, submissions/models.py
While writing a similar bit of code in edx-ora2, I noticed that [filtering on `object.id` up to `id`=`total_len` does not get all entries](https://github.com/edx/edx-ora2/pull/1035/files#r132230976). This way does, and maintains the behavior of limiting the number of results returned in SQL (because [`Slicing an unevaluated QuerySet usually returns another unevaluated QuerySet`](https://docs.djangoproject.com/en/1.11/ref/models/querysets/)
@jibsheet to review, no rush
=> Use sliced all() in management command

submissions/tests/test_api.py
assertItemsEqual() has been renamed to assertCountEqual()
https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertItemsEqual
=> INCR-184: Fix TestCase.assertItemsEqual()

submissions/models.py
In Python 3 it's no longer valid to compare a float with None.
Ref: https://docs.python.org/3/whatsnew/3.0.html#ordering-comparisons
=> INCR-183: Fix comparison of float and None

submissions/__init__.py, submissions/admin.py
https://openedx.atlassian.net/browse/BOM-1619
The allow_tags attribute on methods of ModelAdmin has been deprecated.
Use format_html instead.
=> Fixing: allow_tags attribute on methods of ModelAdmin has been deprecated

submissions/__init__.py, submissions/team_api.py, submissions/tests/test_team_api.py
[EDUCATOR-5059](https://openedx.atlassian.net/browse/EDUCATOR-5059)
Submissions didn't really have much functional change that needed to be done, since it more or less just takes what it's given and stores it, but I wanted to clarify some stuff in the docstring, and change the tests to be reflective of how we actually want the api to be used.
=> EDUCATOR-5059: Teams Submissions are using usernames for submission student_id rather than anonymous user ids

submissions/__init__.py, submissions/models.py, submissions/team_api.py, submissions/tests/test_team_api.py
as a part of https://openedx.atlassian.net/browse/EDUCATOR-5031 I added a function that given a team submission uuid, calls api.reset_score for each submission
=> add function to team api to reset scores

submissions/__init__.py, submissions/team_api.py, submissions/tests/test_read_replica.py, submissions/tests/test_team_api.py
In ORA2, there are cases where we need to retrieve a team submission given regular submission uuid associated with it. This API method does it.
[Jira](https://openedx.atlassian.net/browse/EDUCATOR-5089)
=> Return a team submission given regular submission uuid associated with it

submissions/__init__.py, submissions/models.py, submissions/team_api.py, submissions/tests/test_serializers.py, submissions/tests/test_team_api.py
This is for https://openedx.atlassian.net/browse/EDUCATOR-5207
* Add a function to look up team submission by student item dict
* Add a function to look up the student_ids associated with a team submission
I also added some serializer testing. My original approach for the student_ids was to add it to the serializer, and while I pivoted to an api call, I had already written a decent test for the serializer which we may as well keep.
=> Add some team api functions

README.rst
Updated build status badge to point to GitHub Actions instead of Travis 
JIRA: https://openedx.atlassian.net/browse/BOM-2725
=> chore: updated build status badge to point to GitHub Actions

submissions/__init__.py, submissions/team_api.py, submissions/tests/test_team_api.py
The old get_team_submission_student_ids query would take around 40 seconds. This takes 3 seconds, which is still not good, but it's better.
=> fix: attempt to optimize get_team_submission_student_ids

submissions/__init__.py, submissions/team_api.py, submissions/tests/test_team_api.py
get_teammates_with_submissions_from_other_teams will currently return studentitem entries associated with deleted submissions.
Fix that, and also change the lookup model to Submission for query efficency's sake. The StudentItem query required some subqueries in its filtering, this is a very basic JOIN.
=> fix:get_teammates_with_submissions_from_other_teams returns cancelled submissions

requirements/base.txt, requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/docs.txt, requirements/test.txt, requirements/tox.txt
`Zip` was constrained to <2.0.0 due to python36 but we have already dropped support for python36 and this pin was causing version mismatches in the requirement files so unpinned it and ran make upgrade
=> Fix make upgrade issue and ran make upgrade

submissions/__init__.py, submissions/team_api.py
**TL;DR** fix lookup in `get_team_ids_by_team_submission_uuid`
As part of ESG team support ticket ([AU-493](https://openedx.atlassian.net/browse/AU-493)) I ran into this bug. The delicious irony: we have an outstanding ticket to write tests ([AU-343](https://openedx.atlassian.net/browse/AU-343)) which would have caught this.
**NOTE** writing tests is going to wait until AU-343 for expediency.
=> fix: bug in get_team_ids_by_team_submission_uuid

requirements/pip-tools.txt
The following comment is borrowed from this pull request, with changes: https://github.com/openedx/opaque-keys/pull/218.
This failure started happening in the [automated requirements upgrade GitHub action](https://github.com/openedx/edx-submissions/runs/5704384647?check_suite_focus=true).
The bug was being caused by an interaction between pip and pip-tools, described here: https://github.com/jazzband/pip-tools/issues/1558
The bug is fixed in pip-tools==6.5.0 - from this PR: https://github.com/jazzband/pip-tools/pull/1567
This pull requests bumps the version of pip-tools manually to get the automated upgrades working again.
=> fix: manually update pip-tools version to 6.5.1 to fix pip/pip-tools bug

Makefile, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/docs.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/test.txt, requirements/tox.txt
Updated the upgrade target script to check the compatibility of upgraded pip and pip-tools versions.
For reference, look at this [PR](https://github.com/openedx/edx-repo-health/pull/271) for new check added in edx-repo-health. 
JIRA: https://2u-internal.atlassian.net/browse/BOM-3447
=> fix: Install pip and pip-tools in upgrade script

CONTRIBUTING.rst
We now have a org wide CONTRIBUTING.md that points to our correct
general contributing guidelines.  We don't need repo specific ones that
forward to other contributing docs.
=> docs: Remove repo specific CONTRIBUTING.rst

.github/workflows/ci.yml, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/docs.txt, requirements/pip.txt, requirements/test.txt, requirements/tox.txt, submissions/__init__.py, tox.ini
https://github.com/openedx/edx-platform/issues/32478
Bump the djangorestframework to latest one. To run tests with django4.0+ need this version
https://www.django-rest-framework.org/community/release-notes/?q=parse_header#314x-series
https://www.django-rest-framework.org/community/release-notes/?q=parse_header#3130
=> Upgrading drf to latest version

.github/workflows/migrations-check.yml
- `set-output` has been deprecated by GitHub and it is suggested to be replaced by GitHub.
=> fix: replaced deprecated github actions

.github/workflows/check-reserved-keywords.yml, .github/workflows/ci.yml, .github/workflows/migrations-check.yml, .github/workflows/pypi-publish.yml, Makefile, requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/docs.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/test.txt, requirements/tox.txt, submissions/__init__.py
Adds `ubuntu-24.04` to the list of OS used to run CI and migrations checks.
Where only one OS  `ubuntu-20.04` is configured, replaces it with ` `ubuntu-24.04`.
Closes https://github.com/openedx/edx-submissions/issues/259
Tests passing here should be enough to merge this change, and a successful release to pypi will test the rest.
=> build: adds ubuntu-24.04

submissions/models.py
Per OEP-30 these annotations belong with their models, I'm just moving them from the edx-platform safelist to their correct homes.
=> docs: Add PII annotations

.github/workflows/ci.yml, setup.py, submissions/__init__.py, tox.ini
Support upgrading to django 5.2 while maintaining django 4.2 compatibility.
* ran django-upgrade (no changes)
* added django52 target to tox, CI, and setup docs
* bumps package version
Closes: https://github.com/openedx/edx-submissions/issues/296
See https://discuss.openedx.org/t/django-5-2-upgrade-plan/15397
=> chore: support upgrading to django 5.2
